apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: ingress-role-binding
    # labels:
      # app.kubernetes.io/name: ingress-nginx
      # app.kubernetes.io/part-of: ingress-nginx
    namespace: ingress-space
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: ingress-role
  subjects:
  - kind: ServiceAccount
    name: ingress-serviceaccount
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""