apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
  namespace: production
rules:
- apiGroups:
  - ""
  resources:
  - 'pods'
  - 'services'
  - 'configmaps'
  verbs:
  - 'get'
  - 'watch'
  - 'list'