apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: app-space
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
       containers:
        - name: nginx
          image: nginx:1.17

