---
- name: 'Get join token'
  hosts: master01
  become: true
  gather_facts: false
  tasks:
    - name: Get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: nodes
  become: true
  tasks:
    - name: Join cluster
      shell: "{{ hostvars['master01'].join_command }} >> join_command.txt"