---
- name: 'Reset cluster'
  hosts: all
  become: true
  tasks:
    - name: Reset cluster
      shell: kubeadm reset --force
  tags:
    - reset

- hosts: k8s-master-1
  tasks:
    - name: Delete .kube
      file:
        state: absent
        path: '$HOME/.kube'
  tags:
    - kube